apiVersion: v2
name: varnish
description: A Helm chart for varnish on Kubernetes
home: https://github.com/cresta/varnish

type: application

version: 0.3.2

appVersion: "6.5.1-a"

maintainers:
  - name: cep21
    url: https://github.com/cep21
