name: Test chart changes

on: [push, pull_request]

jobs:
  charttest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v2.3.1
        with:
          command: lint
      - name: Create kind cluster
        uses: helm/kind-action@v1.6.0
      - name: Install helm chart
        run:  helm install varnish ./charts/varnish
      - name: Remove helm chart
        run:  helm uninstall varnish
