apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "varnish.fullname" . }}-varnish
  labels:
    {{- include "varnish.labels" . | nindent 4 }}
data:
{{ toYaml .Values.varnish.vcl | indent 2 }}
