{{- if .Values.nginx.customconfig -}}
{{- else }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "varnish.fullname" . }}-nginx
  labels:
    {{- include "varnish.labels" . | nindent 4 }}
data:
{{ toYaml .Values.nginx.config | indent 2 }}
{{- end }}
