apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "varnish.fullname" . }}
  labels:
    {{- include "varnish.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "varnish.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/varnish: {{ include (print $.Template.BasePath "/configmap-vcl.yaml") . | sha256sum }} 
        checksum/nginx: {{ include (print $.Template.BasePath "/configmap-nginx.yaml") . | sha256sum }} 
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "varnish.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "varnish.serviceAccountName" . }}
      volumes:
        - name: shared-varnish
          emptyDir: {}
        - name: vcl
          configMap:
            name: {{ include "varnish.fullname" . }}-varnish
        - name: nginx
          configMap:
            name: {{ include "varnish.fullname" . }}-nginx
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: varnish
          securityContext:
            {{- toYaml .Values.varnish.securityContext | nindent 12 }}
          image: "{{ .Values.varnish.image.repository }}:{{ .Values.varnish.image.tag }}"
          imagePullPolicy: {{ .Values.varnish.image.pullPolicy }}
          volumeMounts:
            - mountPath: /etc/varnish
              name: vcl
            - mountPath: /var/lib/varnish
              name: shared-varnish
          env:
            - name: VARNISH_SIZE
              value: {{ .Values.varnish.varnishSize | quote }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: varnishncsa
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.varnishncsa.image.repository }}:{{ .Values.varnishncsa.image.tag }}"
          command: ["varnishncsa"]
          imagePullPolicy: {{ .Values.varnishncsa.image.pullPolicy }}
          volumeMounts:
            - mountPath: /var/lib/varnish
              name: shared-varnish
          resources:
            {{- toYaml .Values.varnishncsa.resources | nindent 12 }}
        - name: nginx
          securityContext:
            {{- toYaml .Values.nginx.securityContext | nindent 12 }}
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          volumeMounts:
            - mountPath: /etc/nginx
              name: nginx
          ports:
            - name: http
              containerPort: 81
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
